services:

  webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: webui-simple
    ports: ["3000:8080"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OPENAI_API_BASE_URL=http://host.docker.internal:8000/v1
      - OPENAI_API_KEY=none
      - OPENWEBUI_DEFAULT_MODEL=langchain-llm
      - WEBUI_AUTH=False
    volumes:
      - open-webui:/app/backend/data

volumes:
  open-webui: {}
